<a href="https://colab.research.google.com/github/Slkandu/py/blob/main/pyday3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Syntax
# df = pd.DataFrame(2D_numpy_array)

import numpy as np
import pandas as pd

n1 = np.array([[1,2],[3,4]])

df = pd.DataFrame(n1,columns= ["First Column", "Second Column"])

In [ ]:
df= pd.read_excel("/content/Nfhs District Data.xlsx")

In [ ]:
df.shape

(31, 6)

In [ ]:
df.columns

Index(['KGISDist 1', 'Nfhs District Names',
       'Children under 5 years who are stunted (height-for-age)18 (%)',
       'Children under 5 years who are wasted (weight-for-height)18 (%)',
       'Children under 5 years who are severely wasted (weight-for-height)19 (%)',
       'Children under 5 years who are underweight (weight-for-age)18 (%)'],
      dtype='object')

In [ ]:
df.head()

,KGISDist 1,Nfhs District Names,Children under 5 years who are stunted (height-for-age)18 (%),Children under 5 years who are wasted (weight-for-height)18 (%),Children under 5 years who are severely wasted (weight-for-height)19 (%),Children under 5 years who are underweight (weight-for-age)18 (%)
0,Belagavi,Belgaum,32.78,23.57,10.23,36.88
1,Bagalkot,Bagalkot,48.26,16.85,4.38,42.34
2,Vijayapura,Bijapur,45.94,14.96,4.28,38.96
3,Bidar,Bidar,36.82,22.09,11.14,36.13
4,Raichur,Raichur,39.79,23.23,11.65,40.73

In [ ]:
df.tail()

,KGISDist 1,Nfhs District Names,Children under 5 years who are stunted (height-for-age)18 (%),Children under 5 years who are wasted (weight-for-height)18 (%),Children under 5 years who are severely wasted (weight-for-height)19 (%),Children under 5 years who are underweight (weight-for-age)18 (%)
26,Kolara,Kolar,31.09,15.53,5.81,15.67
27,Chikkaballapura,Chikkaballapura,31.32,16.12,6.08,25.15
28,Bengaluru (Rural),Bangalore Rural,36.57,16.24,9.37,23.84
29,Ramanagara,Ramanagara,15.62,20.01,7.71,19.80
30,Vijayanagara,Vijayanagara,36.08,22.89,13.62,36.51

In [ ]:
df.dtypes

KGISDist 1                                                                   object
Nfhs District Names                                                          object
Children under 5 years who are stunted (height-for-age)18 (%)               float64
Children under 5 years who are wasted (weight-for-height)18 (%)             float64
Children under 5 years who are severely wasted (weight-for-height)19 (%)    float64
Children under 5 years who are underweight (weight-for-age)18 (%)           float64
dtype: object

In [ ]:
# print column names

# Syntax
# df.columns

print(df.columns[2:5])

Index(['Children under 5 years who are stunted (height-for-age)18 (%)',
       'Children under 5 years who are wasted (weight-for-height)18 (%)',
       'Children under 5 years who are severely wasted (weight-for-height)19 (%)'],
      dtype='object')

In [ ]:
# Access Column Data using column name

# Syntax
# df['Column']

series_dis = df['KGISDist 1']

In [ ]:
df.iloc[:,4]

0     10.23
1      4.38
2      4.28
3     11.14
4     11.65
5      3.76
6      4.46
7      4.60
8     13.12
9      3.94
10    13.62
11     8.29
12     3.87
13    13.46
14     5.98
15    11.47
16     3.05
17    11.42
18     5.29
19     5.18
20    15.71
21     9.34
22     7.15
23     6.77
24    12.21
25     7.21
26     5.81
27     6.08
28     9.37
29     7.71
30    13.62
Name: Children under 5 years who are severely wasted (weight-for-height)19 (%), dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 6 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   KGISDist 1                                                                31 non-null     object
 1   Nfhs District Names                                                       31 non-null     object
 2   Children under 5 years who are stunted (height-for-age)18 (%)             31 non-null     float64
 3   Children under 5 years who are wasted (weight-for-height)18 (%)           31 non-null     float64
 4   Children under 5 years who are severely wasted (weight-for-height)19 (%)  31 non-null     float64
 5   Children under 5 years who are underweight (weight-for-age)18 (%)         31 non-null     float64
dtypes: float64(4), object(2)
memory usage: 1.6+ KB

In [ ]:
df.columns

Index(['KGISDist 1', 'Nfhs District Names',
       'Children under 5 years who are stunted (height-for-age)18 (%)',
       'Children under 5 years who are wasted (weight-for-height)18 (%)',
       'Children under 5 years who are severely wasted (weight-for-height)19 (%)',
       'Children under 5 years who are underweight (weight-for-age)18 (%)'],
      dtype='object')

In [ ]:
#  Min, Max, Mean, Std, Median

# Syntax
# df['Column1'].min()

print("Minimum is:",
      df['Children under 5 years who are stunted (height-for-age)18 (%)'].min())

print("Maximum is: ",
      df['Children under 5 years who are stunted (height-for-age)18 (%)'].max())

print("Mean is: ",
      df['Children under 5 years who are stunted (height-for-age)18 (%)'].mean())

print("Standard deviation is: ",
      df['Children under 5 years who are stunted (height-for-age)18 (%)'].std())

print("Median is: ",
      df['Children under 5 years who are stunted (height-for-age)18 (%)'].median())

Minimum is: 15.62
Maximum is:  57.6
Mean is:  34.62322580645161
Standard deviation is:  8.859549795596001
Median is:  32.78

In [ ]:
df.isnull().sum()

KGISDist 1                                                                  0
Nfhs District Names                                                         0
Children under 5 years who are stunted (height-for-age)18 (%)               0
Children under 5 years who are wasted (weight-for-height)18 (%)             0
Children under 5 years who are severely wasted (weight-for-height)19 (%)    0
Children under 5 years who are underweight (weight-for-age)18 (%)           0
dtype: int64